export const HOMESHOES_LOADING = 'HOMESHOES_LOADING';
export const ADDHOME_SHOES= 'ADD_HOMESHOES';
export const HOMESHOES_FAILED = 'HOMESHOES_FAILED';

export const HOMESHORTS_LOADING = 'HOMESHORTS_LOADING';
export const ADDHOME_SHORTS= 'ADDHOME_SHORTS';
export const HOMESHORTS_FAILED = 'HOMESHORTS_FAILED';

export const HOME_TT_LOADING = 'HOME_TT_LOADING';
export const ADD_HOME_TT= 'ADD_HOME_TT';
export const HOME_TT_FAILED = 'HOME_TT_FAILED';
